Repository coopnorge/go-datadog-lib, pull requests merged in 2023-12, with the labels that each got.

#224 chore: Add missing GHA workflow permissions
  .github/workflows/cicd.yaml
Labels: patch, chore

#227 test: Tests started to fail after Datadog-dependency update
  middleware/grpc/client_test.go
  middleware/http/client_test.go
Labels: patch, chore

#228 ci: Remove wrong CI "approval" check
  .policy.yml
Labels: patch

#229 feat: Promote "Experimental Tracing", removing the old legacy-tracing.
  docs/index.md
  internal/context.go
  internal/env.go
  middleware/echo/echo.go
  middleware/echo/echo_test.go
  middleware/grpc/client.go
  middleware/grpc/client_test.go
  middleware/grpc/server.go
  middleware/grpc/server_test.go
  tracing/log.go
  tracing/tracing.go
  tracing/tracing_test.go
Labels: patch, minor, enhancements

#213 Deprecate AppendUserToTrace and make it no-op
  tracing/tracing.go
  tracing/tracing_test.go
Labels: patch

#239 feat: Add Datadog hook for go-logger lib
  go.mod
  go.sum
  tracelogger/hook.go
Labels: minor, enhancements
