Repository coopnorge/go-datadog-lib, pull requests merged in 2024-03, with the labels that each got.

#311 feat: Add utility-function for loading Datadog-config from environment variables
  config/config.go
Labels: release-drafter:minor, release-drafter:enhancements, release-drafter-go:minor

#312 feat: Compare the input-config with environment-variables, and log a warning if they differ.
  bootstrap.go
  config/config.go
  docs/index.md
  internal/env.go
Labels: release-drafter-go:patch, release-drafter:minor, release-drafter:enhancements, release-drafter-go:minor

#324 chore: Request more reviwers
  .policy.yml
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch
