Repository coopnorge/go-datadog-lib, pull requests merged in 2024-02, with the labels that each got.

#284 chore: Fix error formatting
  bootstrap.go
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#282 feat: Add `config.Validate()`
  bootstrap.go
  config/config.go
  config/config_test.go
Labels: release-drafter:minor, release-drafter:enhancements, release-drafter-go:minor, release-drafter-go:major

#265 chore(package): Upgrade to go 1.21
  go.mod
  go.sum
Labels: patch, release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#291 fix: gormtrace panics when nil config is provided
  middleware/gorm/gorm.go
Labels: release-drafter:patch, release-drafter-go:patch, release-drafter:bug-fix
