Repository coopnorge/go-datadog-lib, pull requests merged in 2024-01, with the labels that each got.

#241 feat(grpc): Add additional versions of grpc-interceptors, which are configurable
  middleware/grpc/client.go
  middleware/grpc/options.go
  middleware/grpc/server.go
Labels: minor, enhancements

#246 feat(http): Add additional version of http-wrapper, which is configurable
  .markdownlint.yaml
  README.md
  docs/index.md
  middleware/http/client.go
  middleware/http/options.go
  middleware/http/options_test.go
Labels: minor, enhancements

#253 fix: Deprecated comments
  middleware/grpc/client.go
  middleware/grpc/server.go
  middleware/http/client.go
  tracing/tracing.go
Labels: patch, bug-fix

#255 chore: Update GitHub's GPG key
  .policy.yml
Labels: patch, chore

#260 chore: Deprecate funtions replaced by logger.WithContext
  go.mod
  go.sum
  metric/metric.go
  tracing/log.go
Labels: patch, chore

#264 chore: remove repo's release-drafter configuration
  .github/release-drafter.yml
Labels: patch, chore
