Repository coopnorge/go-datadog-lib, pull requests merged in 2024-04, with the labels that each got.

#326 chore: Reduce the number of users requested to review updates
  .policy.yml
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#323 feat: Allow Datadog integration to be disabled
  bootstrap.go
  docs/index.md
  internal/env.go
  internal/env_test.go
  internal/testhelpers/config.go
  middleware/database/database_test.go
  middleware/echo/echo.go
  middleware/echo/echo_test.go
  middleware/gorm/gorm.go
  middleware/grpc/client.go
  middleware/grpc/client_test.go
  middleware/grpc/server.go
  middleware/grpc/server_test.go
  middleware/http/client.go
  middleware/http/client_test.go
Labels: release-drafter-go:patch, release-drafter:minor, release-drafter:enhancements, release-drafter-go:minor

#335 feat: graceful shutdown of metrics collector
  docs/index.md
  metric/metric.go
  metric/metric_test.go
Labels: release-drafter:minor, release-drafter:enhancements, release-drafter-go:minor

#348 feat: Use go-logger when logging in ddtrace
  bootstrap.go
Labels: release-drafter-go:patch, release-drafter:minor, release-drafter:enhancements
