Repository coopnorge/go-datadog-lib, pull requests merged in 2024-12, with the labels that each got.

#420 test: Add integration-test for gRPC server and HTTP-client
  integration/doc.go
  integration/integration_test.go
Labels: release-drafter:patch, release-drafter:chore

#430 feat: New bootstrap function
  bootstrap.go
  bootstrap_test.go
  docs/index.md
  errors/errors.go
  internal/env.go
  legacy_bootstrap.go
  legacy_bootstrap_test.go
  options.go
Labels: release-drafter:minor, release-drafter:enhancements, release-drafter-go:minor

#450 fix: Use testhelpers to configure Datadog
  bootstrap_test.go
  internal/testhelpers/config.go
Labels: release-drafter:patch, release-drafter-go:patch, release-drafter:bug-fix

#447 docs: Rephrase documentation
  README.md
  bootstrap.go
  docs/index.md
  example_test.go
  go.mod
  go.sum
  legacy_bootstrap.go
  middleware/database/example_test.go
  middleware/echo/example_test.go
  middleware/gorm/example_test.go
  middleware/grpc/example_client_test.go
  middleware/grpc/example_server_test.go
  middleware/http/example_test.go
  tracelogger/example_test.go
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#458 docs: Remove DD_AGENT_HOST info
  docs/index.md
  internal/env.go
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch
