Repository coopnorge/go-datadog-lib, pull requests merged in 2025-04, with the labels that each got.

#523 refactor: Define tests in `_test` packages
  bootstrap_test.go
  config/config_test.go
  integration/integration_test.go
  legacy_bootstrap_test.go
  metric/datadog_test.go
  metric/metric_test.go
  metrics/metrics_test.go
  middleware/database/database_test.go
  middleware/echo/echo_test.go
  middleware/grpc/client_test.go
  middleware/grpc/server_test.go
  middleware/http/client_test.go
  middleware/http/options_test.go
  tracing/log_test.go
  tracing/tracing_test.go
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#387 chore: Use mage for CI
  .github/workflows/cicd.yaml
  README.md
  bootstrap.go
  go.mod
  go.sum
  legacy_bootstrap.go
  magefiles/magefile.go
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:minor

#453 feat: Normalize "DD_TRACE_AGENT_URL" to work with both unix-scheme prefix and not.
  bootstrap.go
  bootstrap_internal_test.go
  config/config.go
  docs/index.md
  legacy_bootstrap.go
  legacy_bootstrap_internal_test.go
Labels: release-drafter-go:patch, release-drafter:minor, release-drafter:enhancements

#535 refactor: Simplify metric-options
  metrics/metrics.go
  metrics/metrics_internal_test.go
  metrics/options.go
  metrics/options_test.go
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:major

#524 feat!: Allow more customization per metric-report
  metrics/example_test.go
  metrics/metrics.go
  metrics/metrics_internal_test.go
  metrics/metrics_test.go
  metrics/options.go
  metrics/options_test.go
Labels: release-drafter:minor, release-drafter:enhancements, release-drafter-go:major, release-drafter:breaking-change
