Repository coopnorge/go-datadog-lib, pull requests merged in 2025-02, with the labels that each got.

#479 chore: Pin GitHub actions to a hash
  .github/workflows/cicd.yaml
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#477 chore: Change security-scan workflow to inherit secrets
  .github/workflows/security-scan.yaml
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#481 chore(deps): Bump Go to 1.23
  go.mod
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch, release-drafter:dependency

#488 docs: Clarify the StopFunc expectations
  bootstrap.go
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#492 chore: Add missing workflow permissions
  .github/workflows/cicd.yaml
  .github/workflows/security-scan.yaml
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#496 fix: Do not log full URL in span-tags
  middleware/http/client_test.go
  middleware/http/options.go
Labels: release-drafter:patch, release-drafter-go:patch, release-drafter:bug-fix
